import React, { useState } from 'react';
import { Copy, Download, ChevronDown, ChevronUp, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function ThreatReport({ report }) {
  const [expanded, setExpanded] = useState(false);

  if (!report) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(report.full_report);
  };

  const handleDownload = () => {
    const content = [
      report.executive_summary ? `EXECUTIVE SUMMARY\n${report.executive_summary}\n\n` : '',
      report.full_report || ''
    ].join('');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mobileguard_report_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-card backdrop-blur-xl p-8 rounded-2xl border border-white/5 flex flex-col shadow-xl print:bg-white print:text-black">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-500/20 rounded-lg print:hidden">
            <FileText className="w-6 h-6 text-blue-400" />
          </div>
          <div>
            <h3 className="font-bold text-xl text-white print:text-black">Threat Intelligence Report</h3>
            <p className="text-xs text-muted print:text-gray-500">ID: {report.report_id || `REP-${Date.now().toString().slice(-6)}`}</p>
          </div>
        </div>
        
        <div className="flex gap-3 print:hidden">
          <button 
            onClick={handleCopy} 
            className="flex items-center gap-2 px-4 py-2 bg-secondary hover:bg-secondary/80 border border-white/5 rounded-xl transition-all text-sm font-medium"
          >
            <Copy className="w-4 h-4" /> Copy
          </button>
          <button 
            onClick={handleDownload} 
            className="flex items-center gap-2 px-4 py-2 bg-accent hover:bg-accent/80 text-white rounded-xl transition-all shadow-lg shadow-accent/20 text-sm font-bold"
          >
            <Download className="w-4 h-4" /> Export
          </button>
        </div>
      </div>
      
      {report.executive_summary && (
        <div className="bg-[#0A121F] border border-white/5 p-6 rounded-xl mb-6 relative overflow-hidden print:bg-gray-100 print:border-black">
          <div className="absolute left-0 top-0 bottom-0 w-1 bg-accent"></div>
          <h4 className="text-xs font-bold uppercase tracking-widest text-muted mb-3 print:text-gray-600">Executive Summary</h4>
          <p className="text-white/90 text-sm leading-relaxed print:text-black">{report.executive_summary}</p>
        </div>
      )}

      <button 
        onClick={() => setExpanded(!expanded)}
        className="flex items-center justify-between w-full p-4 bg-secondary/50 hover:bg-secondary rounded-xl transition-colors border border-white/5 print:hidden group"
      >
        <span className="font-semibold text-sm group-hover:text-white transition-colors">Detailed Findings & Artifacts</span>
        {expanded ? <ChevronUp className="w-5 h-5 text-muted" /> : <ChevronDown className="w-5 h-5 text-muted" />}
      </button>

      <AnimatePresence>
        {(expanded) && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden print:h-auto print:opacity-100"
          >
            <div className="mt-4 p-6 bg-[#050A10] border border-white/5 rounded-xl">
              <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed text-textSecondary print:text-black">
                {report.full_report}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      
      {/* For printing purposes, always render it if print mode, though CSS print rules handle it better natively sometimes. */}
      <div className="hidden print:block mt-6">
         <pre className="whitespace-pre-wrap font-mono text-[13px] leading-relaxed text-black">
            {report.full_report}
          </pre>
      </div>

      <div className="mt-8 pt-6 border-t border-white/5 flex justify-between items-center text-xs text-muted print:text-gray-400 print:border-black print:mt-12">
        <span>Generated by MobileGuard AI Engine</span>
        <span>{new Date(report.report_generated_at || Date.now()).toLocaleString()}</span>
      </div>
    </div>
  );
}
